language: node_js
node_js:
  - "node"
install:
  - "npm install"
script: npm run build
# deploy:
#   skip_cleanup: true
#   provider: firebase
#   token:
#     secure: 1/yrxSmDSVr7CKJoKL12ZQlHEcmHZKh4rztyKkNdlEzzxb2C6mP1Sp5Ty-Fr7fdlOy
notifications:
  email: false
branches:
  only:
    master