import React, { Component } from 'react';

import './index.css';
import Grid from '../grid';
import ColorList from '../colors';

const test = {
  image: [
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}
  ],
  colors: {
    0: "#578dd1",
    1: "#bfbfbf",
    2: "#1173be",
    3: "#fff",
    4: "#000"
  }
}

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      colors: Object.values(test.colors),
      activeColorId: 0
    };

    this.setActiveColor = this.setActiveColor.bind(this);
  }

  setActiveColor(id) {
    console.log(id); // eslint-disable-line
    this.setState({
      activeColorId: id
    });
  }

  render() {
    return (
      <div className="App">
        <Grid
          image={test.image}
          colors={this.state.colors}
          activeColorId={this.state.activeColorId}
        />
        <ColorList
          colors={this.state.colors}
          activeColorId={this.state.activeColorId}
          setActiveColor={this.setActiveColor}
        />
      </div>
    );
  }
}

export default App;
