const images = [{
  image: [
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}
  ],
  colors: {
    0: "#578dd1", //light-blue
    1: "#bfbfbf", //gray
    2: "#1173be", //dark-blue
    3: "#fff",
    4: "#000"
  },
  stats: {
    0: 0,
    1: 0,
    2: 0,
    3: 0,
    4: 0
  }
}, {
  image: [
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 0, filled: false}, {color: 0, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 1, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 2, filled: false}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 4, filled: true }, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true},
    {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}, {color: 3, filled: true}
  ],
  colors: {
    0: "#E799D6", //light-pink
    1: "#bfbfbf", //gray
    2: "#D682BF", //dark-pink
    3: "#fff",
    4: "#000"
  },
  stats: {
    0: 0,
    1: 0,
    2: 0,
    3: 0,
    4: 0
  }
}]

export default images;